name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Command running";
      - name: Node
        run: node -v && npm -v
      # - name: Checkout
      - uses: actions/checkout@v3
        # with:
          # Make sure the actual branch is checked out when running on pull requests
          # ref: ${{ github.head_ref }}
      - run: ls -a
      - run: npm i
      # - name: NPP
      # - run: npx jest
      # - name: CI
      - run: npm run ci

      # - name: Prettify code
        # uses: creyD/prettier_action@v4.3
        # with:
          # This part is also where you can pass other options, for example:
          # prettier_options: --write **/*.{js,md}
